import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

import ResponsiveAppBar from "../containers/menu";
import Search from "../containers/search";
import Categories from "../containers/categories";
import SpacingGrid from "../containers/grid";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ResponsiveAppBar />
        <Search />
        <div style={{ width: "100%" }}>
          <Categories />
        </div>
        <SpacingGrid />
        <div>Footer [conventional]</div>
      </main>
    </>
  );
}
